server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: order
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/pays/**, 
        - id: product
          uri: http://localhost:8084
          predicates:
            - Path=/inventories/**, 
        - id: sale
          uri: http://localhost:8085
          predicates:
            - Path=/sales/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/pays/**, 
        - id: product
          uri: http://product:8080
          predicates:
            - Path=/inventories/**, 
        - id: sale
          uri: http://sale:8080
          predicates:
            - Path=/sales/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
